version: '3.8'

services:
  postgres-test:
    image: postgres:16.8-alpine
    environment:
      POSTGRES_DB: contacts_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app-test:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      postgres-test:
        condition: service_healthy
      elasticsearch-test:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=integration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-test:5432/contacts_db_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch-test:9200
    command: ["java", "-jar", "app.jar", "--spring.profiles.active=integration"] 