spring:
  application:
    name: contact-search

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/contacts_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: HikariCP-Test

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true

  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://elasticsearch:9200}

server:
  port: ${SERVER_PORT:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days in milliseconds

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.security: DEBUG
